services:
  client:
    build: ./client
    ports:
      - "5173:5173"    
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ./.env # can specify diff env files
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      # POSTGRES_DB: docker
      # POSTGRES_USER: postgres
    # secrets:

volumes:
  my_db_data:
    external: true